name: create-release
on:
  push:
    branches:
      - main
jobs:
  generate_manpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./setup.bash --generate-release ${{ secrets.GITHUB_TOKEN }}